id: AC6965060
base_file: fCF3C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:36:02.454721
  last_modified_at: 2022-06-11 13:36:02.454727
